### ISSUE TITLE
No default option for verbose

### ISSUE THREAD

**Issue by baderj** [mallocator/gulp-international#3]
Building fails, when option ``verbose`` is not set, e.g., as in the example code
```
var gulp = require('gulp');
var international = require('gulp-international');

gulp.task('default', function () {
	return gulp.src('src/file.ext')
		.pipe(international())
		.pipe(gulp.dest('dist'));
});
```
Result:
```
▶ gulp              
[08:21:32] Using gulpfile ~/site/gulpfile.js
[08:21:32] Starting 'default'...
[08:21:32] 'default' errored after 7.69 ms
[08:21:32] TypeError: Cannot read property 'verbose' of undefined
    at module.exports (/home/user//site/node_modules/gulp-international/index.js:359:11)
    at /home/user/site/gulpfile.js:6:15
    at taskWrapper (/home/user/site/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (domain.js:301:14)
    at runBound (domain.js:314:12)
    at asyncRunner (/home/user/site/node_modules/async-done/index.js:55:18)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

Setting the verbosity manually fixes the issue, i.e., ``international({"verbose": false})``.

My version number are: 

- gulp: 4.0.0
- gulp-international: 1.1.0
- npm versions: 6.4.1

**Comment by tchapi** [comment]
+1, same behaviour here !
